name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: 'Create env file'
        run: |
          touch .env
          echo GENIUS_ACCESS_TOKEN=${{ secrets.GENIUS_ACCESS_TOKEN }} >> .env
          cat .env
    - run: pip install nox==2019.11.9
    - run: pip install poetry==1.0.5
    - name: Install dependencies using Poetry
      run: poetry install --ansi
    - name: Run tests
      run: poetry run pytest --cov
